### ISSUE TITLE
pip

### ISSUE THREAD

**Issue by Zakaria-ouertani** [ziyaankhadim/Squid-Game#1]
pip

**Comment by ziyaankhadim** [comment]
This repository is not in Python.
Its in JavaScript using Three.js.

**To Install dependencies (only the first time)
npm install

**To Run the local server at localhost:8080
npm run dev

**Comment by Zakaria-ouertani** [comment]
nah just said pip

**Comment by Zakaria-ouertani** [comment]
nah just said pip
